import  libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Connect to MySQL

In [2]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
load_dotenv()
engin=create_engine(f"mysql+pymysql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}"
    f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

clean data

In [3]:
user_data=pd.read_csv('data/users.csv')

In [4]:
user_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             10000 non-null  object
 1   signup_date         10000 non-null  object
 2   country             10000 non-null  object
 3   age_group           10000 non-null  object
 4   gender              10000 non-null  object
 5   device_type         10000 non-null  object
 6   operating_system    10000 non-null  object
 7   subscription_type   10000 non-null  object
 8   preferred_language  10000 non-null  object
 9   referral_source     10000 non-null  object
dtypes: object(10)
memory usage: 781.4+ KB

In [5]:
user_data.describe()

,user_id,signup_date,country,age_group,gender,device_type,operating_system,subscription_type,preferred_language,referral_source
count,10000,10000,10000,10000,10000,10000,10000,10000,10000,10000
unique,10000,180,6,4,4,3,4,2,4,5
top,USR_00001,2025-04-23,US,25-34,Female,Mobile,iOS,Free,English,App Store
freq,1,72,4003,4052,5536,8491,5309,6466,7500,2941

In [6]:
user_data.head(5)

,user_id,signup_date,country,age_group,gender,device_type,operating_system,subscription_type,preferred_language,referral_source
0,USR_00001,2025-04-13,CA,25-34,Female,Tablet,iOS,Free,Spanish,App Store
1,USR_00002,2025-06-29,US,25-34,Male,Mobile,Android,Free,English,App Store
2,USR_00003,2025-04-03,UK,45+,Female,Mobile,iOS,Free,English,Google Ads
3,USR_00004,2025-01-15,US,35-44,Male,Mobile,iOS,Premium,English,TikTok
4,USR_00005,2025-04-17,US,35-44,Male,Mobile,iOS,Free,English,Google Ads

In [7]:
# checking null value 
user_data.isnull().sum()

user_id               0
signup_date           0
country               0
age_group             0
gender                0
device_type           0
operating_system      0
subscription_type     0
preferred_language    0
referral_source       0
dtype: int64

In [8]:
#check duplicate
user_data.duplicated().sum()

np.int64(0)

In [9]:
user_data.shape

(10000, 10)

In [10]:
user_data.columns

Index(['user_id', 'signup_date', 'country', 'age_group', 'gender',
       'device_type', 'operating_system', 'subscription_type',
       'preferred_language', 'referral_source'],
      dtype='object')

In [11]:
user_data['user_id'].isnull().sum()

np.int64(0)

In [12]:
#Check unique
user_data['age_group'].unique()

array(['25-34', '45+', '35-44', '18-24'], dtype=object)

In [13]:
user_data['age_group'].value_counts()

age_group
25-34    4052
18-24    2878
35-44    2039
45+      1031
Name: count, dtype: int64

In [14]:
user_data['country'].unique()

array(['CA', 'US', 'UK', 'IN', 'AU', 'DE'], dtype=object)

In [15]:
user_data['country'].value_counts()

country
US    4003
IN    1971
UK    1571
DE     979
CA     971
AU     505
Name: count, dtype: int64

In [16]:
user_data['device_type'].value_counts()

device_type
Mobile     8491
Desktop    1012
Tablet      497
Name: count, dtype: int64

In [17]:
user_data['gender'].value_counts()

gender
Female               5536
Male                 3488
Non-binary            493
Prefer not to say     483
Name: count, dtype: int64

In [18]:
user_data['operating_system'].value_counts()

operating_system
iOS        5309
Android    3679
Windows     715
MacOS       297
Name: count, dtype: int64

In [19]:
user_data['preferred_language'].value_counts()

preferred_language
English    7500
Spanish    1031
Hindi       954
German      515
Name: count, dtype: int64

In [20]:
user_data['referral_source'].value_counts()

referral_source
App Store     2941
Instagram     2052
TikTok        2022
Google Ads    1971
Organic       1014
Name: count, dtype: int64

In [21]:
user_data['subscription_type'].value_counts()

subscription_type
Free       6466
Premium    3534
Name: count, dtype: int64

In [22]:
user_data['signup_date']=pd.to_datetime(user_data['signup_date'])

In [23]:
user_data['signup_date'].describe()

count                            10000
mean     2025-04-01 06:51:33.119999744
min                2025-01-01 00:00:00
25%                2025-02-16 00:00:00
50%                2025-04-02 00:00:00
75%                2025-05-17 00:00:00
max                2025-06-29 00:00:00
Name: signup_date, dtype: object

In [24]:
user_data['age_group'].dtype

dtype('O')

subscriptions data

In [25]:
sub_data=pd.read_csv('data/subscriptions.csv')

In [26]:
sub_data.head(5)

,subscription_id,user_id,subscription_type,subscription_start_date,subscription_end_date,payment_method,premium_offer_shown,premium_offer_clicked,upgraded_to_premium
0,SUB_0001,USR_07386,Annual Premium,2025-01-06,2025-02-05,Credit Card,1,1,1
1,SUB_0002,USR_02766,Monthly Premium,2025-04-21,2025-05-21,Google Pay,1,1,1
2,SUB_0003,USR_05734,Monthly Premium,2025-03-15,NaN,Credit Card,1,1,1
3,SUB_0004,USR_01452,Monthly Premium,2025-06-17,2025-07-17,Credit Card,1,1,1
4,SUB_0005,USR_03933,Monthly Premium,2025-02-22,2025-03-24,PayPal,1,1,1

In [27]:
sub_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   subscription_id          3000 non-null   object
 1   user_id                  3000 non-null   object
 2   subscription_type        3000 non-null   object
 3   subscription_start_date  3000 non-null   object
 4   subscription_end_date    1025 non-null   object
 5   payment_method           3000 non-null   object
 6   premium_offer_shown      3000 non-null   int64
 7   premium_offer_clicked    3000 non-null   int64
 8   upgraded_to_premium      3000 non-null   int64
dtypes: int64(3), object(6)
memory usage: 211.1+ KB

In [28]:
sub_data.describe(include=object)

,subscription_id,user_id,subscription_type,subscription_start_date,subscription_end_date,payment_method
count,3000,3000,3000,3000,1025,3000
unique,3000,3000,2,189,186,4
top,SUB_0001,USR_07386,Monthly Premium,2025-05-31,2025-05-12,Credit Card
freq,1,1,2415,31,16,1500

In [29]:
sub_data.shape

(3000, 9)

In [30]:
sub_data.isnull().sum()

subscription_id               0
user_id                       0
subscription_type             0
subscription_start_date       0
subscription_end_date      1975
payment_method                0
premium_offer_shown           0
premium_offer_clicked         0
upgraded_to_premium           0
dtype: int64

In [31]:
query='SHOW DATABASES'
pd.read_sql(query,engin)

                              Database
0   ai_chatbot_user_retention_analysis
1                              company
2                            dbms_exam
3                               ddl_pr
4                           de_project
5                                 demo
6                   information_schema
7                                mysql
8             online_learning_platform
9                   performance_schema
10                              sakila
11                              school
12                                 sys
13                                test
14                       tomorrow_exam
15                                uber
16                               world

In [32]:
sub_data.to_sql('ai_chatbot_user_retention_analysis',con=engin,if_exists='append',index=False)
pd.read_sql('select * from  ai_chatbot_user_retention_analysis LIMIT 10 ',engin)

,subscription_id,user_id,subscription_type,subscription_start_date,subscription_end_date,payment_method,premium_offer_shown,premium_offer_clicked,upgraded_to_premium
0,SUB_0001,USR_07386,Annual Premium,2025-01-06,2025-02-05,Credit Card,1,1,1
1,SUB_0002,USR_02766,Monthly Premium,2025-04-21,2025-05-21,Google Pay,1,1,1
2,SUB_0003,USR_05734,Monthly Premium,2025-03-15,None,Credit Card,1,1,1
3,SUB_0004,USR_01452,Monthly Premium,2025-06-17,2025-07-17,Credit Card,1,1,1
4,SUB_0005,USR_03933,Monthly Premium,2025-02-22,2025-03-24,PayPal,1,1,1
5,SUB_0006,USR_05402,Monthly Premium,2025-06-27,None,Credit Card,1,1,1
6,SUB_0007,USR_04391,Annual Premium,2025-02-25,None,Apple Pay,1,1,1
7,SUB_0008,USR_00532,Monthly Premium,2025-04-12,2025-05-12,Apple Pay,1,1,1
8,SUB_0009,USR_08627,Monthly Premium,2025-02-02,2025-03-04,Credit Card,1,1,1
9,SUB_0010,USR_01030,Monthly Premium,2025-02-13,2025-03-15,Credit Card,1,1,1

In [33]:
from sqlalchemy import text
with engin.connect() as con:
  con.execute(text('drop table ai_chatbot_user_retention_analysis'))

In [34]:
pd.read_sql('show tables',engin)

  Tables_in_ai_chatbot_user_retention_analysis
0                                     sec_date
1                                     sub_data

In [35]:
query="select subscription_type,subscription_start_date,subscription_end_date	from sub_data where subscription_end_date is null LIMIT 10"
pd.read_sql(query,engin)

  subscription_type subscription_start_date subscription_end_date
0   Monthly Premium              2025-03-15                  None
1   Monthly Premium              2025-06-27                  None
2    Annual Premium              2025-02-25                  None
3    Annual Premium              2025-02-22                  None
4   Monthly Premium              2025-06-20                  None
5   Monthly Premium              2025-01-08                  None
6   Monthly Premium              2025-05-02                  None
7   Monthly Premium              2025-05-14                  None
8    Annual Premium              2025-03-13                  None
9    Annual Premium              2025-04-04                  None

In [36]:
query='select subscription_type,subscription_start_date,subscription_end_date from sub_data where subscription_end_date is not null LIMIT 10'
pd.read_sql(query,engin)

  subscription_type subscription_start_date subscription_end_date
0    Annual Premium              2025-01-06            2025-02-05
1   Monthly Premium              2025-04-21            2025-05-21
2   Monthly Premium              2025-06-17            2025-07-17
3   Monthly Premium              2025-02-22            2025-03-24
4   Monthly Premium              2025-04-12            2025-05-12
5   Monthly Premium              2025-02-02            2025-03-04
6   Monthly Premium              2025-02-13            2025-03-15
7   Monthly Premium              2025-03-28            2025-04-27
8   Monthly Premium              2025-01-20            2025-02-19
9   Monthly Premium              2025-02-25            2025-03-27

In [37]:
query='select subscription_type,subscription_start_date,subscription_end_date from sub_data where subscription_end_date is not null and subscription_type = "Annual Premium"  LIMIT 10'
pd.read_sql(query,engin)

  subscription_type subscription_start_date subscription_end_date
0    Annual Premium              2025-01-06            2025-02-05
1    Annual Premium              2025-03-27            2025-04-26
2    Annual Premium              2025-05-16            2025-06-15
3    Annual Premium              2025-01-10            2025-02-09
4    Annual Premium              2025-06-24            2025-07-24
5    Annual Premium              2025-03-10            2025-04-09
6    Annual Premium              2025-04-30            2025-05-30
7    Annual Premium              2025-06-07            2025-07-07
8    Annual Premium              2025-01-16            2025-02-15
9    Annual Premium              2025-04-03            2025-05-03

In [38]:
sub_data['subscription_start_date']=pd.to_datetime(sub_data['subscription_start_date'])
sub_data['subscription_end_date']=pd.to_datetime(sub_data['subscription_end_date'])

In [39]:
query="SELECT subscription_type,AVG(DATEDIFF(subscription_end_date, subscription_start_date)) AS avg_date FROM sub_data WHERE subscription_end_date IS NOT NULL GROUP BY subscription_type"
pd.read_sql(query,engin)

  subscription_type  avg_date
0    Annual Premium      30.0
1   Monthly Premium      30.0

In [40]:
#"I first analyzed the existing records, found that all subscriptions had a 30-day duration regardless of type, identified a possible data quality issue, and chose an imputation method that preserved the observed pattern in the dataset."

In [41]:
query = '''
SELECT
    subscription_type,
    MAX(DATEDIFF(subscription_end_date, subscription_start_date)) AS max_date,
    MIN(DATEDIFF(subscription_end_date, subscription_start_date)) AS min_date,
    AVG(DATEDIFF(subscription_end_date, subscription_start_date)) AS avg_date
FROM sub_data
WHERE subscription_end_date IS NOT NULL
GROUP BY subscription_type;
'''

pd.read_sql(query, engin)

  subscription_type  max_date  min_date  avg_date
0    Annual Premium        30        30      30.0
1   Monthly Premium        30        30      30.0

In [42]:
query=' select 	subscription_type, count(*) as missing_val from sub_data where subscription_end_date is null group by 	subscription_type'
pd.read_sql(query,engin)

  subscription_type  missing_val
0   Monthly Premium         3148
1    Annual Premium          802

In [43]:
#i thing subscription_end_date is not that much importan for find the solution so now keep it null move to the next operation

In [44]:
sub_data.columns

Index(['subscription_id', 'user_id', 'subscription_type',
       'subscription_start_date', 'subscription_end_date', 'payment_method',
       'premium_offer_shown', 'premium_offer_clicked', 'upgraded_to_premium'],
      dtype='object')

In [45]:
user_data.duplicated().sum()

np.int64(0)

In [46]:
sub_data['payment_method'].value_counts()

payment_method
Credit Card    1500
Apple Pay       740
Google Pay      468
PayPal          292
Name: count, dtype: int64

In [47]:
sub_data['premium_offer_shown'].value_counts()

premium_offer_shown
1    3000
Name: count, dtype: int64

In [48]:
sub_data['premium_offer_clicked'].value_counts()

premium_offer_clicked
1    2708
0     292
Name: count, dtype: int64

In [49]:
sub_data['upgraded_to_premium'].value_counts()

upgraded_to_premium
1    3000
Name: count, dtype: int64

In [50]:
not_subscriber=user_data.shape[0]-sub_data.shape[0]
print(f'total nummber of  not subscriber is:{not_subscriber}')

total nummber of  not subscriber is:7000

In [51]:
user_data.shape[0]

10000

In [52]:
sec_date=pd.read_csv('data/sessions.csv')

In [53]:
sec_date.head()

,session_id,user_id,session_number,session_start,session_duration_minutes,session_end,app_version,login_method,network_quality,crash_occurred
0,SES_000001,USR_01096,1,2025-01-31 19:49:00,11,2025-01-31 20:00:00,v2.1.0,Google,Fair,0
1,SES_000002,USR_08848,1,2025-05-01 01:06:00,9,2025-05-01 01:15:00,v2.3.0,Biometrics,Poor,0
2,SES_000003,USR_00387,1,2025-06-28 12:08:00,9,2025-06-28 12:17:00,v2.3.0,Apple ID,Good,0
3,SES_000004,USR_05324,1,2025-04-28 22:15:00,25,2025-04-28 22:40:00,v2.2.0,Google,Good,0
4,SES_000005,USR_08602,1,2025-02-10 02:22:00,12,2025-02-10 02:34:00,v2.1.0,Biometrics,Fair,0

In [54]:
sec_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 10 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   session_id                150000 non-null  object
 1   user_id                   150000 non-null  object
 2   session_number            150000 non-null  int64
 3   session_start             150000 non-null  object
 4   session_duration_minutes  150000 non-null  int64
 5   session_end               150000 non-null  object
 6   app_version               150000 non-null  object
 7   login_method              150000 non-null  object
 8   network_quality           150000 non-null  object
 9   crash_occurred            150000 non-null  int64
dtypes: int64(3), object(7)
memory usage: 11.4+ MB

In [55]:
sec_date.describe(include=object)

,session_id,user_id,session_start,session_end,app_version,login_method,network_quality
count,150000,150000,150000,150000,150000,150000,150000
unique,150000,9369,118466,118508,3,4,3
top,SES_000001,USR_02465,2025-05-11 23:45:00,2025-04-20 01:08:00,v2.3.0,Google,Good
freq,1,174,7,6,78299,59936,105433

In [56]:
sec_date.shape

(150000, 10)

In [58]:
sec_date['session_number'].value_counts()

session_number
1      9369
2      8752
3      8203
4      7703
5      7237
       ...
170       1
171       1
172       1
173       1
174       1
Name: count, Length: 174, dtype: int64

In [59]:
sec_date['session_number']

0           1
1           1
2           1
3           1
4           1
         ...
149995     31
149996     49
149997     24
149998     38
149999    125
Name: session_number, Length: 150000, dtype: int64

In [60]:
sec_date

,session_id,user_id,session_number,session_start,session_duration_minutes,session_end,app_version,login_method,network_quality,crash_occurred
0,SES_000001,USR_01096,1,2025-01-31 19:49:00,11,2025-01-31 20:00:00,v2.1.0,Google,Fair,0
1,SES_000002,USR_08848,1,2025-05-01 01:06:00,9,2025-05-01 01:15:00,v2.3.0,Biometrics,Poor,0
2,SES_000003,USR_00387,1,2025-06-28 12:08:00,9,2025-06-28 12:17:00,v2.3.0,Apple ID,Good,0
3,SES_000004,USR_05324,1,2025-04-28 22:15:00,25,2025-04-28 22:40:00,v2.2.0,Google,Good,0
4,SES_000005,USR_08602,1,2025-02-10 02:22:00,12,2025-02-10 02:34:00,v2.1.0,Biometrics,Fair,0
...,...,...,...,...,...,...,...,...,...,...
149995,SES_149996,USR_09832,31,2025-03-29 05:55:00,5,2025-03-29 06:00:00,v2.2.0,Biometrics,Poor,0
149996,SES_149997,USR_07927,49,2025-08-11 22:26:00,24,2025-08-11 22:50:00,v2.3.0,Apple ID,Poor,0
149997,SES_149998,USR_09381,24,2025-06-05 18:31:00,10,2025-06-05 18:41:00,v2.3.0,Apple ID,Good,0
149998,SES_149999,USR_04715,38,2025-04-27 18:34:00,6,2025-04-27 18:40:00,v2.2.0,Email,Poor,0
149999,SES_150000,USR_04738,125,2025-06-15 09:36:00,5,2025-06-15 09:41:00,v2.3.0,Google,Good,0

In [61]:
sec_date.to_sql('sec_Date',con=engin,if_exists='append',index=False)
pd.read_sql('select * from  sec_date LIMIT 10 ',engin)

C:\Users\VISHVA.S\AppData\Local\Temp\ipykernel_17864\1880010435.py:1: UserWarning: The provided table name 'sec_Date' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  sec_date.to_sql('sec_Date',con=engin,if_exists='append',index=False)

,session_id,user_id,session_number,session_start,session_duration_minutes,session_end,app_version,login_method,network_quality,crash_occurred
0,SES_000001,USR_01096,1,2025-01-31 19:49:00,11,2025-01-31 20:00:00,v2.1.0,Google,Fair,0
1,SES_000002,USR_08848,1,2025-05-01 01:06:00,9,2025-05-01 01:15:00,v2.3.0,Biometrics,Poor,0
2,SES_000003,USR_00387,1,2025-06-28 12:08:00,9,2025-06-28 12:17:00,v2.3.0,Apple ID,Good,0
3,SES_000004,USR_05324,1,2025-04-28 22:15:00,25,2025-04-28 22:40:00,v2.2.0,Google,Good,0
4,SES_000005,USR_08602,1,2025-02-10 02:22:00,12,2025-02-10 02:34:00,v2.1.0,Biometrics,Fair,0
5,SES_000006,USR_06342,1,2025-04-06 19:03:00,8,2025-04-06 19:11:00,v2.2.0,Biometrics,Fair,0
6,SES_000007,USR_04924,1,2025-04-06 22:29:00,4,2025-04-06 22:33:00,v2.2.0,Email,Good,0
7,SES_000008,USR_01307,1,2025-01-29 21:12:00,9,2025-01-29 21:21:00,v2.1.0,Google,Good,0
8,SES_000009,USR_06607,1,2025-02-28 05:53:00,16,2025-02-28 06:09:00,v2.1.0,Google,Fair,0
9,SES_000010,USR_06003,1,2025-03-06 15:15:00,18,2025-03-06 15:33:00,v2.2.0,Google,Poor,0

In [62]:
query='show tables from ai_chatbot_user_retention_analysis'
pd.read_sql(query,engin)

  Tables_in_ai_chatbot_user_retention_analysis
0                                     sec_date
1                                     sub_data

In [63]:
query = "SELECT * FROM sec_date LIMIT 10"
pd.read_sql(query, engin)

,session_id,user_id,session_number,session_start,session_duration_minutes,session_end,app_version,login_method,network_quality,crash_occurred
0,SES_000001,USR_01096,1,2025-01-31 19:49:00,11,2025-01-31 20:00:00,v2.1.0,Google,Fair,0
1,SES_000002,USR_08848,1,2025-05-01 01:06:00,9,2025-05-01 01:15:00,v2.3.0,Biometrics,Poor,0
2,SES_000003,USR_00387,1,2025-06-28 12:08:00,9,2025-06-28 12:17:00,v2.3.0,Apple ID,Good,0
3,SES_000004,USR_05324,1,2025-04-28 22:15:00,25,2025-04-28 22:40:00,v2.2.0,Google,Good,0
4,SES_000005,USR_08602,1,2025-02-10 02:22:00,12,2025-02-10 02:34:00,v2.1.0,Biometrics,Fair,0
5,SES_000006,USR_06342,1,2025-04-06 19:03:00,8,2025-04-06 19:11:00,v2.2.0,Biometrics,Fair,0
6,SES_000007,USR_04924,1,2025-04-06 22:29:00,4,2025-04-06 22:33:00,v2.2.0,Email,Good,0
7,SES_000008,USR_01307,1,2025-01-29 21:12:00,9,2025-01-29 21:21:00,v2.1.0,Google,Good,0
8,SES_000009,USR_06607,1,2025-02-28 05:53:00,16,2025-02-28 06:09:00,v2.1.0,Google,Fair,0
9,SES_000010,USR_06003,1,2025-03-06 15:15:00,18,2025-03-06 15:33:00,v2.2.0,Google,Poor,0

In [ ]:
print('user count:',user_data.shape[0])
print('sessions count:',sec_date.shape[0])

user count: 10000
sessions count: 150000

In [65]:
sec_date.isnull().sum()

session_id                  0
user_id                     0
session_number              0
session_start               0
session_duration_minutes    0
session_end                 0
app_version                 0
login_method                0
network_quality             0
crash_occurred              0
dtype: int64

In [67]:
sec_date.duplicated().sum()

np.int64(0)

In [71]:
sec_date['user_id'].value_counts()

user_id
USR_02465    174
USR_09643    160
USR_02664    153
USR_04738    125
USR_05963    120
            ...
USR_01029      1
USR_05003      1
USR_03615      1
USR_00996      1
USR_04390      1
Name: count, Length: 9369, dtype: int64

In [80]:
query="select session_id,session_number, user_id from sec_date where user_id ='USR_02465' limit 10 "
pd.read_sql(query,engin)

   session_id  session_number    user_id
0  SES_001160               1  USR_02465
1  SES_001274               2  USR_02465
2  SES_001513               3  USR_02465
3  SES_001629               4  USR_02465
4  SES_002580               5  USR_02465
5  SES_004347               6  USR_02465
6  SES_005489               7  USR_02465
7  SES_005812               8  USR_02465
8  SES_006824               9  USR_02465
9  SES_007183              10  USR_02465

In [82]:
query='select * from sub_data limit 10'
pd.read_sql(query,engin)

,subscription_id,user_id,subscription_type,subscription_start_date,subscription_end_date,payment_method,premium_offer_shown,premium_offer_clicked,upgraded_to_premium
0,SUB_0001,USR_07386,Annual Premium,2025-01-06,2025-02-05,Credit Card,1,1,1
1,SUB_0002,USR_02766,Monthly Premium,2025-04-21,2025-05-21,Google Pay,1,1,1
2,SUB_0003,USR_05734,Monthly Premium,2025-03-15,None,Credit Card,1,1,1
3,SUB_0004,USR_01452,Monthly Premium,2025-06-17,2025-07-17,Credit Card,1,1,1
4,SUB_0005,USR_03933,Monthly Premium,2025-02-22,2025-03-24,PayPal,1,1,1
5,SUB_0006,USR_05402,Monthly Premium,2025-06-27,None,Credit Card,1,1,1
6,SUB_0007,USR_04391,Annual Premium,2025-02-25,None,Apple Pay,1,1,1
7,SUB_0008,USR_00532,Monthly Premium,2025-04-12,2025-05-12,Apple Pay,1,1,1
8,SUB_0009,USR_08627,Monthly Premium,2025-02-02,2025-03-04,Credit Card,1,1,1
9,SUB_0010,USR_01030,Monthly Premium,2025-02-13,2025-03-15,Credit Card,1,1,1

In [85]:
query="select * from sub_data where user_id='USR_02465'or user_id='USR_09643'"
pd.read_sql(query,engin)

Empty DataFrame
Columns: [subscription_id, user_id, subscription_type, subscription_start_date, subscription_end_date, payment_method, premium_offer_shown, premium_offer_clicked, upgraded_to_premium]
Index: []

In [86]:
max_val=sec_date['user_id'].value_counts()

In [91]:
max_val[:1]

user_id
USR_02465    174
Name: count, dtype: int64

In [93]:
# cleaning retention data 
ret_data=pd.read_csv('data/retention.csv')

In [95]:
ret_data.head()

,user_id,total_sessions,returned_next_day,returned_after_7_days,returned_after_30_days,days_until_last_session,churned,churn_reason
0,USR_00001,11,0,0,0,118,0,Not Churned
1,USR_00002,45,0,0,1,104,0,Not Churned
2,USR_00003,9,0,0,0,13,0,Not Churned
3,USR_00004,10,0,0,0,8,0,Not Churned
4,USR_00005,1,0,0,0,0,1,Found another app

In [96]:
ret_data.shape

(10000, 8)

In [97]:
ret_data.isnull().sum()

user_id                    0
total_sessions             0
returned_next_day          0
returned_after_7_days      0
returned_after_30_days     0
days_until_last_session    0
churned                    0
churn_reason               0
dtype: int64

In [99]:
ret_data.duplicated().sum()

np.int64(0)

In [100]:
ret_data['churn_reason'].value_counts()

churn_reason
Not Churned               7237
Found another app          546
AI responses unhelpful     519
Slow response times        515
Just trying it out         502
App crashes/Bugs           418
Too expensive              263
Name: count, dtype: int64

In [ ]:
#Initial Observation: Out of approximately 10,000 users, only around 3,000 are premium subscribers. Since premium users have invested in the service, they may be more likely to remain active despite minor issues. This leads to the hypothesis that the decline in user count may be more significant among free users. This hypothesis will be verified through retention, session, conversation, and feedback analysis.